import { WardPatient } from './ward-patient-list.models';

export const WARD_PATIENT_WARD_OPTIONS = ['Peads Ward', 'General Ward', 'ICU Ward'];

export const WARD_PATIENT_SHIFT_OPTIONS = ['Day Shift', 'Evening Shift', 'Night Shift'];

/** TODO: Replace with WardPatientListService API integration when backend ward patient endpoints are available. */
export function createInitialWardPatients(): WardPatient[] {
  const base: WardPatient[] = [
    {
      admissionId: 'adm-001',
      patientId: 'pat-001',
      patientName: 'Zahan Bakhat',
      mrn: 'PPS-2024-0001',
      bedNo: 'A-1',
      wardName: 'Peads Ward',
      roomName: 'Room 101',
      galleryName: 'Gallery A - Male',
      age: 5,
      sex: 'M',
      diagnosis: 'ALRI',
      doctorId: 'doc-aoun',
      doctorName: 'Dr Aoun',
      nurseId: 'nurse-ayesha',
      nurseName: 'Ayesha',
      admittedOn: '2026-06-10',
      status: 'stable',
      medicationsDue: 2,
      vitalsDue: 1,
      dripsRunning: 0,
      nursingTasksDue: 1,
      criticalAlerts: 0,
    },
    {
      admissionId: 'adm-002',
      patientId: 'pat-002',
      patientName: 'Ali Raza',
      mrn: 'PPS-2024-0002',
      bedNo: 'A-2',
      wardName: 'Peads Ward',
      roomName: 'Room 101',
      galleryName: 'Gallery A - Male',
      age: 32,
      sex: 'M',
      diagnosis: 'Dengue Fever',
      doctorId: 'doc-aoun',
      doctorName: 'Dr Aoun',
      nurseId: 'nurse-imran',
      nurseName: 'Imran',
      admittedOn: '2026-06-11',
      status: 'stable',
      medicationsDue: 1,
      vitalsDue: 0,
      dripsRunning: 1,
      nursingTasksDue: 0,
      criticalAlerts: 0,
    },
    {
      admissionId: 'adm-003',
      patientId: 'pat-003',
      patientName: 'Ahmed Khan',
      mrn: 'PPS-2024-0003',
      bedNo: 'A-4',
      wardName: 'Peads Ward',
      roomName: 'Room 102',
      galleryName: 'Gallery A - Male',
      age: 45,
      sex: 'M',
      diagnosis: 'Pneumonia',
      doctorId: 'doc-aoun',
      doctorName: 'Dr Aoun',
      nurseId: 'nurse-ayesha',
      nurseName: 'Ayesha',
      admittedOn: '2026-06-12',
      status: 'watch',
      medicationsDue: 3,
      vitalsDue: 2,
      dripsRunning: 1,
      nursingTasksDue: 2,
      criticalAlerts: 1,
    },
    {
      admissionId: 'adm-004',
      patientId: 'pat-004',
      patientName: 'Sara Fatima',
      mrn: 'PPS-2024-0004',
      bedNo: 'B-1',
      wardName: 'Peads Ward',
      roomName: 'Room 103',
      galleryName: 'Gallery B - Female',
      age: 28,
      sex: 'F',
      diagnosis: 'Post C-Section',
      doctorId: 'doc-sana',
      doctorName: 'Dr Sana',
      nurseId: 'nurse-fatima',
      nurseName: 'Fatima',
      admittedOn: '2026-06-11',
      status: 'stable',
      medicationsDue: 1,
      vitalsDue: 1,
      dripsRunning: 0,
      nursingTasksDue: 1,
      criticalAlerts: 0,
    },
    {
      admissionId: 'adm-005',
      patientId: 'pat-005',
      patientName: 'Maria Bibi',
      mrn: 'PPS-2024-0005',
      bedNo: 'PR-201',
      wardName: 'Peads Ward',
      roomName: 'Private 201',
      galleryName: 'Private Wing',
      age: 70,
      sex: 'F',
      diagnosis: 'Hypertension',
      doctorId: 'doc-aoun',
      doctorName: 'Dr Aoun',
      nurseId: 'nurse-imran',
      nurseName: 'Imran',
      admittedOn: '2026-06-09',
      status: 'stable',
      medicationsDue: 2,
      vitalsDue: 0,
      dripsRunning: 0,
      nursingTasksDue: 0,
      criticalAlerts: 0,
    },
    {
      admissionId: 'adm-006',
      patientId: 'pat-006',
      patientName: 'Yasir Ahmed',
      mrn: 'PPS-2024-0006',
      bedNo: 'ICU-2',
      wardName: 'Peads Ward',
      roomName: 'ICU Bay 2',
      galleryName: 'ICU Wing',
      age: 62,
      sex: 'M',
      diagnosis: 'COPD Exacerbation',
      doctorId: 'doc-aoun',
      doctorName: 'Dr Aoun',
      nurseId: 'nurse-fahim',
      nurseName: 'Fahim',
      admittedOn: '2026-06-08',
      status: 'watch',
      medicationsDue: 4,
      vitalsDue: 2,
      dripsRunning: 2,
      nursingTasksDue: 3,
      criticalAlerts: 1,
    },
    {
      admissionId: 'adm-007',
      patientId: 'pat-007',
      patientName: 'Nadeem Akhtar',
      mrn: 'PPS-2024-0007',
      bedNo: 'PR-202',
      wardName: 'Peads Ward',
      roomName: 'Private 202',
      galleryName: 'Private Wing',
      age: 60,
      sex: 'M',
      diagnosis: 'Diabetes Mellitus',
      doctorId: 'doc-irfan',
      doctorName: 'Dr Irfan',
      nurseId: 'nurse-hina',
      nurseName: 'Hina',
      admittedOn: '2026-06-06',
      status: 'dischargePlanned',
      medicationsDue: 0,
      vitalsDue: 1,
      dripsRunning: 0,
      nursingTasksDue: 1,
      criticalAlerts: 0,
    },
  ];

  const extras: WardPatient[] = [
    mk('adm-008', 'Hassan Ali', 'PPS-2024-0008', 'A-3', 'Room 101', 'Gallery A - Male', 8, 'M', 'AURTI', 'Dr Aoun', 'Ayesha', '2026-06-12', 'stable'),
    mk('adm-009', 'Amina Noor', 'PPS-2024-0009', 'B-2', 'Room 103', 'Gallery B - Female', 12, 'F', 'Gastroenteritis', 'Dr Sana', 'Fatima', '2026-06-10', 'stable'),
    mk('adm-010', 'Bilal Hussain', 'PPS-2024-0010', 'A-5', 'Room 102', 'Gallery A - Male', 14, 'M', 'Fracture Femur', 'Dr Aoun', 'Imran', '2026-06-07', 'stable'),
    mk('adm-011', 'Khadija Shah', 'PPS-2024-0011', 'B-3', 'Room 103', 'Gallery B - Female', 9, 'F', 'Typhoid Fever', 'Dr Sana', 'Sana', '2026-06-11', 'stable'),
    mk('adm-012', 'Usman Tariq', 'PPS-2024-0012', 'A-6', 'Room 101', 'Gallery A - Male', 16, 'M', 'Appendicitis Post-Op', 'Dr Aoun', 'Ayesha', '2026-06-09', 'stable'),
    mk('adm-013', 'Hira Malik', 'PPS-2024-0013', 'B-4', 'Room 104', 'Gallery B - Female', 7, 'F', 'Asthma', 'Dr Sana', 'Fatima', '2026-06-13', 'stable'),
    mk('adm-014', 'Rayyan Khan', 'PPS-2024-0014', 'A-7', 'Room 102', 'Gallery A - Male', 4, 'M', 'Febrile Illness', 'Dr Aoun', undefined, '2026-06-13', 'stable'),
    mk('adm-015', 'Mehak Raza', 'PPS-2024-0015', 'B-5', 'Room 104', 'Gallery B - Female', 11, 'F', 'UTI', 'Dr Sana', 'Hina', '2026-06-08', 'stable'),
    mk('adm-016', 'Arham Siddiqui', 'PPS-2024-0016', 'ICU-1', 'ICU Bay 1', 'ICU Wing', 3, 'M', 'Sepsis', 'Dr Aoun', 'Fahim', '2026-06-12', 'watch'),
    mk('adm-017', 'Zainab Ali', 'PPS-2024-0017', 'PR-203', 'Private 203', 'Private Wing', 55, 'F', 'CKD', 'Dr Irfan', 'Imran', '2026-06-05', 'stable'),
    mk('adm-018', 'Hamza Iqbal', 'PPS-2024-0018', 'A-8', 'Room 101', 'Gallery A - Male', 10, 'M', 'Cellulitis', 'Dr Aoun', 'Ayesha', '2026-06-11', 'stable'),
    mk('adm-019', 'Noor Fatima', 'PPS-2024-0019', 'B-6', 'Room 104', 'Gallery B - Female', 6, 'F', 'Dehydration', 'Dr Sana', undefined, '2026-06-14', 'stable'),
    mk('adm-020', 'Saad Ahmed', 'PPS-2024-0020', 'A-9', 'Room 102', 'Gallery A - Male', 13, 'M', 'Malaria', 'Dr Aoun', 'Imran', '2026-06-10', 'stable'),
    mk('adm-021', 'Laiba Khan', 'PPS-2024-0021', 'B-7', 'Room 103', 'Gallery B - Female', 15, 'F', 'Anemia', 'Dr Sana', 'Fatima', '2026-06-07', 'stable'),
    mk('adm-022', 'Omar Farooq', 'PPS-2024-0022', 'PR-204', 'Private 204', 'Private Wing', 48, 'M', 'MI Recovery', 'Dr Irfan', 'Hina', '2026-06-04', 'stable'),
    mk('adm-023', 'Sana Javed', 'PPS-2024-0023', 'A-10', 'Room 104', 'Gallery A - Male', 17, 'M', 'Dengue Fever', 'Dr Aoun', 'Ayesha', '2026-06-13', 'stable'),
  ];

  return [...base, ...extras];
}

function mk(
  admissionId: string,
  patientName: string,
  mrn: string,
  bedNo: string,
  roomName: string,
  galleryName: string,
  age: number,
  sex: 'M' | 'F',
  diagnosis: string,
  doctorName: string,
  nurseName: string | undefined,
  admittedOn: string,
  status: WardPatient['status']
): WardPatient {
  const doctorId = doctorName.toLowerCase().replace(/\s+/g, '-');
  return {
    admissionId,
    patientId: admissionId.replace('adm', 'pat'),
    patientName,
    mrn,
    bedNo,
    wardName: 'Peads Ward',
    roomName,
    galleryName,
    age,
    sex,
    diagnosis,
    doctorId,
    doctorName,
    nurseId: nurseName ? nurseName.toLowerCase() : undefined,
    nurseName,
    admittedOn,
    status,
    medicationsDue: status === 'stable' ? 1 : 2,
    vitalsDue: status === 'watch' ? 2 : 1,
    dripsRunning: status === 'watch' ? 1 : 0,
    nursingTasksDue: nurseName ? 1 : 2,
    criticalAlerts: status === 'watch' ? 1 : 0,
  };
}
