import { WardBedRecord, WardGalleryOption, WardRoomRecord } from './ward-bed-management.models';

export const WARD_BED_WARD_OPTIONS = ['Peads Ward', 'General Ward', 'ICU Ward'];

export const WARD_BED_GALLERY_OPTIONS: WardGalleryOption[] = [
  { id: 'gallery-a-male', label: 'Gallery A - Male' },
  { id: 'gallery-b-female', label: 'Gallery B - Female' },
  { id: 'private-wing', label: 'Private Wing' },
  { id: 'icu-wing', label: 'ICU Wing' },
];

/** TODO: Replace with WardBedManagementService API integration when backend bed endpoints are available. */
export function createInitialWardRooms(): WardRoomRecord[] {
  return [
    {
      id: 'room-101',
      wardId: 'peads',
      wardName: 'Peads Ward',
      galleryId: 'gallery-a-male',
      galleryName: 'Gallery A - Male',
      roomName: 'Room 101',
      roomType: 'general',
      capacity: 6,
      dailyCharge: 2500,
      floor: '2',
      description: 'General male ward room',
      occupiedBeds: 4,
      availableBeds: 2,
      cleaningBeds: 0,
      maintenanceBeds: 0,
      onHoldBeds: 0,
      status: 'active',
    },
    {
      id: 'room-102',
      wardId: 'peads',
      wardName: 'Peads Ward',
      galleryId: 'gallery-a-male',
      galleryName: 'Gallery A - Male',
      roomName: 'Room 102',
      roomType: 'general',
      capacity: 6,
      dailyCharge: 2500,
      floor: '2',
      description: 'General male ward room',
      occupiedBeds: 3,
      availableBeds: 1,
      cleaningBeds: 1,
      maintenanceBeds: 0,
      onHoldBeds: 1,
      status: 'active',
    },
    {
      id: 'room-103',
      wardId: 'peads',
      wardName: 'Peads Ward',
      galleryId: 'gallery-a-male',
      galleryName: 'Gallery A - Male',
      roomName: 'Room 103',
      roomType: 'general',
      capacity: 6,
      dailyCharge: 2500,
      floor: '2',
      description: 'General male ward room',
      occupiedBeds: 2,
      availableBeds: 4,
      cleaningBeds: 0,
      maintenanceBeds: 0,
      onHoldBeds: 0,
      status: 'active',
    },
    {
      id: 'room-104',
      wardId: 'peads',
      wardName: 'Peads Ward',
      galleryId: 'gallery-a-male',
      galleryName: 'Gallery A - Male',
      roomName: 'Room 104',
      roomType: 'private',
      capacity: 4,
      dailyCharge: 4500,
      floor: '2',
      description: 'Private room block',
      occupiedBeds: 3,
      availableBeds: 0,
      cleaningBeds: 0,
      maintenanceBeds: 1,
      onHoldBeds: 0,
      status: 'active',
    },
  ];
}

export function createInitialWardBeds(): WardBedRecord[] {
  return [
    {
      id: 'bed-101-1',
      roomId: 'room-101',
      bedNo: '101-1',
      bedType: 'standard',
      status: 'occupied',
      patientName: 'Zohan Baig',
      age: 24,
      sex: 'M',
      nurseName: 'Ayesha Malik',
      admissionId: 'adm-101-1',
      occupiedSince: '2026-06-10',
      dailyCharge: 2500,
    },
    {
      id: 'bed-101-2',
      roomId: 'room-101',
      bedNo: '101-2',
      bedType: 'standard',
      status: 'occupied',
      patientName: 'Ali Raza',
      age: 31,
      sex: 'M',
      nurseName: 'Imran Ali',
      admissionId: 'adm-101-2',
      occupiedSince: '2026-06-11',
      dailyCharge: 2500,
    },
    {
      id: 'bed-101-3',
      roomId: 'room-101',
      bedNo: '101-3',
      bedType: 'standard',
      status: 'occupied',
      patientName: 'Ahmed Khan',
      age: 45,
      sex: 'M',
      nurseName: 'Fahim Noor',
      admissionId: 'adm-101-3',
      occupiedSince: '2026-06-12',
      dailyCharge: 2500,
    },
    {
      id: 'bed-101-4',
      roomId: 'room-101',
      bedNo: '101-4',
      bedType: 'standard',
      status: 'occupied',
      patientName: 'Nadeem Akhtar',
      age: 60,
      sex: 'M',
      nurseName: 'Hina Tariq',
      admissionId: 'adm-101-4',
      occupiedSince: '2026-06-06',
      dailyCharge: 2500,
    },
    {
      id: 'bed-101-5',
      roomId: 'room-101',
      bedNo: '101-5',
      bedType: 'standard',
      status: 'available',
      dailyCharge: 2500,
    },
    {
      id: 'bed-101-6',
      roomId: 'room-101',
      bedNo: '101-6',
      bedType: 'standard',
      status: 'available',
      dailyCharge: 2500,
    },
    {
      id: 'bed-102-1',
      roomId: 'room-102',
      bedNo: '102-1',
      bedType: 'standard',
      status: 'occupied',
      patientName: 'Usman Ali',
      age: 29,
      sex: 'M',
      nurseName: 'Sana Khan',
      admissionId: 'adm-102-1',
      occupiedSince: '2026-06-09',
      dailyCharge: 2500,
    },
    {
      id: 'bed-102-2',
      roomId: 'room-102',
      bedNo: '102-2',
      bedType: 'standard',
      status: 'occupied',
      patientName: 'Bilal Hussain',
      age: 38,
      sex: 'M',
      nurseName: 'Marwa Shah',
      admissionId: 'adm-102-2',
      occupiedSince: '2026-06-08',
      dailyCharge: 2500,
    },
    {
      id: 'bed-102-3',
      roomId: 'room-102',
      bedNo: '102-3',
      bedType: 'standard',
      status: 'occupied',
      patientName: 'Kamran Siddiqui',
      age: 42,
      sex: 'M',
      nurseName: 'Rabia Noor',
      admissionId: 'adm-102-3',
      occupiedSince: '2026-06-07',
      dailyCharge: 2500,
    },
    {
      id: 'bed-102-4',
      roomId: 'room-102',
      bedNo: '102-4',
      bedType: 'standard',
      status: 'available',
      dailyCharge: 2500,
    },
    {
      id: 'bed-102-5',
      roomId: 'room-102',
      bedNo: '102-5',
      bedType: 'standard',
      status: 'on_hold',
      dailyCharge: 2500,
      notes: 'Reserved for incoming admission',
    },
    {
      id: 'bed-102-6',
      roomId: 'room-102',
      bedNo: '102-6',
      bedType: 'standard',
      status: 'cleaning',
      dailyCharge: 2500,
    },
    {
      id: 'bed-103-1',
      roomId: 'room-103',
      bedNo: '103-1',
      bedType: 'pediatric',
      status: 'occupied',
      patientName: 'Hassan Raza',
      age: 8,
      sex: 'M',
      nurseName: 'Ayesha Malik',
      admissionId: 'adm-103-1',
      occupiedSince: '2026-06-11',
      dailyCharge: 2500,
    },
    {
      id: 'bed-103-2',
      roomId: 'room-103',
      bedNo: '103-2',
      bedType: 'pediatric',
      status: 'occupied',
      patientName: 'Ayan Malik',
      age: 10,
      sex: 'M',
      nurseName: 'Sana Khan',
      admissionId: 'adm-103-2',
      occupiedSince: '2026-06-10',
      dailyCharge: 2500,
    },
    {
      id: 'bed-103-3',
      roomId: 'room-103',
      bedNo: '103-3',
      bedType: 'standard',
      status: 'available',
      dailyCharge: 2500,
    },
    {
      id: 'bed-103-4',
      roomId: 'room-103',
      bedNo: '103-4',
      bedType: 'standard',
      status: 'available',
      dailyCharge: 2500,
    },
    {
      id: 'bed-103-5',
      roomId: 'room-103',
      bedNo: '103-5',
      bedType: 'standard',
      status: 'available',
      dailyCharge: 2500,
    },
    {
      id: 'bed-103-6',
      roomId: 'room-103',
      bedNo: '103-6',
      bedType: 'standard',
      status: 'available',
      dailyCharge: 2500,
    },
    {
      id: 'bed-104-1',
      roomId: 'room-104',
      bedNo: '104-1',
      bedType: 'standard',
      status: 'occupied',
      patientName: 'Farhan Iqbal',
      age: 52,
      sex: 'M',
      nurseName: 'Hina Tariq',
      admissionId: 'adm-104-1',
      occupiedSince: '2026-06-05',
      dailyCharge: 4500,
    },
    {
      id: 'bed-104-2',
      roomId: 'room-104',
      bedNo: '104-2',
      bedType: 'standard',
      status: 'occupied',
      patientName: 'Tariq Mehmood',
      age: 48,
      sex: 'M',
      nurseName: 'Imran Ali',
      admissionId: 'adm-104-2',
      occupiedSince: '2026-06-04',
      dailyCharge: 4500,
    },
    {
      id: 'bed-104-3',
      roomId: 'room-104',
      bedNo: '104-3',
      bedType: 'standard',
      status: 'occupied',
      patientName: 'Shahid Anwar',
      age: 57,
      sex: 'M',
      nurseName: 'Fahim Noor',
      admissionId: 'adm-104-3',
      occupiedSince: '2026-06-03',
      dailyCharge: 4500,
    },
    {
      id: 'bed-104-4',
      roomId: 'room-104',
      bedNo: '104-4',
      bedType: 'standard',
      status: 'maintenance',
      dailyCharge: 4500,
      notes: 'AC repair in progress',
    },
  ];
}
